version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_install:
      - pip install shibuya

sphinx:
  builder: dirhtml
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements-dev.lock
