name: Deploy docs to Pages

on:
  push:
    branches:
    - master

  workflow_dispatch:

permissions:
  contents: read
  deployments: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: build docs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm ci
    - run: npm run build

    - uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: install deps
      run: python -m pip install -r requirements.txt

    - name: install theme
      run: python -m pip install .

    - name: build docs
      run: sphinx-build docs _site -b dirhtml

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1

  deploy:
    environment:
      name: cloudflare-pages
      url: ${{ steps.deployment.outputs.url }}

    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to Cloudflare Pages
      id: deployment
      uses: cloudflare/pages-action@v1.3.0
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName:  shibuya-doc
        directory: _site
